/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Labelled machine translation shown UNDER a quoted source passage (the original is always shown).
         *     Identifiers (standard numbers, clauses, units, numbers) are protected; results are cached per language.
         */
        post: operations["translate_api_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voice Status Endpoint */
        get: operations["voice_status_endpoint_api_voice_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/stt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Stt
         * @description Transcribe one recording. `lang`: en | hi | kn, or empty to let the model detect it.
         */
        post: operations["voice_stt_api_voice_stt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voice Tts */
        post: operations["voice_tts_api_voice_tts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Summary
         * @description Latest evaluation results written by `bisense eval` (docs/eval/latest.json). Real numbers only.
         */
        get: operations["eval_summary_api_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/trace/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Trace */
        get: operations["debug_trace_api_debug_trace__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Endpoint */
        post: operations["search_endpoint_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Endpoint */
        post: operations["ask_endpoint_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Standards */
        get: operations["list_standards_api_standards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_standards_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Standard Detail */
        get: operations["standard_detail_api_standards__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/clauses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Clauses
         * @description Every clause of a document, in order, with verbatim text (the explorer's clause viewer).
         */
        get: operations["all_clauses_api_standards__slug__clauses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/clauses/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clause */
        get: operations["clause_api_standards__slug__clauses__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requirements */
        get: operations["requirements_api_standards__slug__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/requirements/plain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requirements Plain
         * @description AI interpretations of requirement statements (labelled as such in the UI).
         */
        get: operations["requirements_plain_api_standards__slug__requirements_plain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/requirements.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requirements Csv */
        get: operations["requirements_csv_api_standards__slug__requirements_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_standards__slug__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{slug}/pages/{n}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Image */
        get: operations["page_image_api_standards__slug__pages__n__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmendmentOut */
        AmendmentOut: {
            /** Label */
            label: string;
            /** Date */
            date: string | null;
            /** Text Excerpt */
            text_excerpt: string | null;
            /** Page */
            page: number | null;
        };
        /** Answer */
        Answer: {
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "answer" | "standards_list" | "requirements" | "comparison" | "summary" | "definition" | "clarification" | "insufficient_evidence" | "out_of_scope";
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Points */
            points: components["schemas"]["Point"][];
            /** Standards */
            standards: components["schemas"]["StandardRef"][];
            /** Gaps */
            gaps: string[];
            /** Clarifying Question */
            clarifying_question: string | null;
            /** Clarifying Options */
            clarifying_options: string[];
            /** Follow Ups */
            follow_ups: string[];
            /**
             * Evidence Strength
             * @default none
             * @enum {string}
             */
            evidence_strength: "strong" | "moderate" | "limited" | "none";
            /**
             * Strength Basis
             * @default
             */
            strength_basis: string;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "cached" | "extractive" | "none";
            /** Provider */
            provider: string | null;
            /** Generated At */
            generated_at: string | null;
            /**
             * Dropped Count
             * @default 0
             */
            dropped_count: number;
            /** Drops */
            drops: components["schemas"]["Drop"][];
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
            /**
             * Translated
             * @default false
             */
            translated: boolean;
            /**
             * Translation Failed
             * @default false
             */
            translation_failed: boolean;
            original: components["schemas"]["OriginalAnswer"] | null;
            /** Notice */
            notice: string | null;
            /**
             * Searched Summary
             * @default
             */
            searched_summary: string;
            /**
             * Library Note
             * @default
             */
            library_note: string;
            /**
             * Synthetic Used
             * @default false
             */
            synthetic_used: boolean;
            /** Coverage */
            coverage: components["schemas"]["CoverageNote"][];
        };
        /**
         * AskContext
         * @description What the client remembers about the conversation. Only questions and standard ids -- never answers.
         */
        AskContext: {
            /** Recent Questions */
            recent_questions?: string[];
            /** Focus Slugs */
            focus_slugs?: string[];
            /** Open Slug */
            open_slug?: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Query */
            query: string;
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
            context?: components["schemas"]["AskContext"] | null;
        };
        /**
         * AskTrace
         * @description Everything the Retrieval details drawer shows (also served by /api/debug/trace when DEBUG=true).
         */
        AskTrace: {
            /** Request Id */
            request_id: string;
            query: components["schemas"]["QueryInfo"];
            /** Candidates */
            candidates: components["schemas"]["Citation"][];
            /** Cited Ids */
            cited_ids: string[];
            /** Drops */
            drops: components["schemas"]["Drop"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "cached" | "extractive" | "none";
            /** Provider */
            provider: string | null;
            timings: components["schemas"]["Timings"];
            /** Top Rerank */
            top_rerank: number | null;
            /** Gate Threshold */
            gate_threshold: number;
            /** Tokens */
            tokens: {
                [key: string]: number;
            };
        };
        /** Body_voice_stt_api_voice_stt_post */
        Body_voice_stt_api_voice_stt_post: {
            /** Audio */
            audio: string;
            /** Lang */
            lang?: string | null;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
        };
        /** Citation */
        Citation: {
            /** Id */
            id: string;
            /** N */
            n: number;
            /** Slug */
            slug: string;
            /** Standard Number */
            standard_number: string | null;
            /** Standard Title */
            standard_title: string;
            /**
             * Standard Kind
             * @enum {string}
             */
            standard_kind: "standard" | "guidance" | "order" | "catalogue";
            /** Clause Number */
            clause_number: string;
            /** Clause Heading */
            clause_heading: string;
            /** Clause Kind */
            clause_kind: string;
            /** Clause Path */
            clause_path: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Snippet */
            snippet: string;
            scores: components["schemas"]["Scores"];
            /** Synthetic */
            synthetic: boolean;
            /** Tier */
            tier: string;
            /** Doc Type */
            doc_type: string;
            /** Url */
            url: string | null;
            /** Has Page Image */
            has_page_image: boolean;
            /**
             * Text Scope
             * @default full_text
             */
            text_scope: string;
            /** Document Title */
            document_title: string | null;
            /** Source Org */
            source_org: string | null;
            /** Source Type */
            source_type: string | null;
            /**
             * Source Label
             * @default
             */
            source_label: string;
        };
        /** ClauseNode */
        ClauseNode: {
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Heading */
            heading: string;
            /** Kind */
            kind: string;
            /** Level */
            level: number;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Children */
            children: components["schemas"]["ClauseNode"][];
        };
        /** ClauseOut */
        ClauseOut: {
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Heading */
            heading: string;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /** Level */
            level: number;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Text */
            text: string;
            /** Is Table */
            is_table: boolean;
            /** Children */
            children: components["schemas"]["ClauseNode"][];
        };
        /** CompareCell */
        CompareCell: {
            /** Text */
            text: string | null;
            /** Citations */
            citations: string[];
            /** Found */
            found: boolean;
        };
        /** CompareRequest */
        CompareRequest: {
            /** A */
            a: string;
            /** B */
            b: string;
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
        };
        /** CompareResponse */
        CompareResponse: {
            a: components["schemas"]["StandardSummary"];
            b: components["schemas"]["StandardSummary"];
            /** Rows */
            rows: components["schemas"]["CompareRow"][];
            /** Numeric */
            numeric: components["schemas"]["NumericRow"][];
            /** Key Differences */
            key_differences: components["schemas"]["Point"][];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "cached" | "extractive" | "none";
            /** Notice */
            notice: string | null;
            /**
             * Dropped Count
             * @default 0
             */
            dropped_count: number;
        };
        /** CompareRow */
        CompareRow: {
            /** Aspect */
            aspect: string;
            a: components["schemas"]["CompareCell"];
            b: components["schemas"]["CompareCell"];
        };
        /** CompulsoryEvidence */
        CompulsoryEvidence: {
            /** Status */
            status: string;
            /** Source */
            source: string | null;
            /** Slug */
            slug: string | null;
            /** Clause Number */
            clause_number: string | null;
        };
        /** CoverageNote */
        CoverageNote: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /** Text Scope */
            text_scope: string;
        };
        /** Drop */
        Drop: {
            /** Field */
            field: string;
            /** Text */
            text: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "no_index";
            /** Dataset Mode */
            dataset_mode: string;
            /** Index Version */
            index_version: string | null;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Llm */
            llm: {
                [key: string]: boolean | string | null;
            };
            /** Models Loaded */
            models_loaded: boolean;
            /** Demo Mode */
            demo_mode: boolean;
            /** Version */
            version: string;
            /** Features */
            features: {
                [key: string]: boolean;
            };
            voice: components["schemas"]["VoiceStatus"] | null;
            /** Translation */
            translation: {
                [key: string]: boolean | string | null;
            };
            /** Languages */
            languages: {
                [key: string]: {
                    [key: string]: boolean;
                };
            };
            /** Retrieval */
            retrieval: {
                [key: string]: string | null;
            };
        };
        /** LibraryOut */
        LibraryOut: {
            /** Coverage */
            coverage: string;
            /** Dataset Mode */
            dataset_mode: string;
            /** Index Version */
            index_version: string;
            /** Built At */
            built_at: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Categories */
            categories: components["schemas"]["CategoryCount"][];
            /** Languages */
            languages: ("en" | "hi" | "kn")[];
            /** Sources */
            sources: {
                [key: string]: string | null;
            }[];
        };
        /** NumericRow */
        NumericRow: {
            /** Parameter */
            parameter: string;
            /** Unit */
            unit: string | null;
            /** A Value */
            a_value: string | null;
            /** B Value */
            b_value: string | null;
            /** A Citation */
            a_citation: string | null;
            /** B Citation */
            b_citation: string | null;
        };
        /** OriginalAnswer */
        OriginalAnswer: {
            /** Summary */
            summary: string;
            /** Points */
            points: components["schemas"]["Point"][];
            /** Gaps */
            gaps: string[];
            /** Follow Ups */
            follow_ups: string[];
        };
        /** Point */
        Point: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "source_fact" | "interpretation";
            /** Text */
            text: string;
            /** Citations */
            citations: string[];
            /** Quote */
            quote: string | null;
        };
        /** Provenance */
        Provenance: {
            /** Tier */
            tier: string;
            /** Doc Type */
            doc_type: string | null;
            /** File Name */
            file_name: string | null;
            /** Source Url */
            source_url: string | null;
            /** Obtained On */
            obtained_on: string | null;
            /** Pages */
            pages: number | null;
            /** Language */
            language: string | null;
            /** Warnings */
            warnings: string[];
            /** Document Title */
            document_title: string | null;
            /** Source Org */
            source_org: string | null;
            /** Source Type */
            source_type: string | null;
            /**
             * Verification Status
             * @default unverified
             */
            verification_status: string;
            /** Access Note */
            access_note: string | null;
            /**
             * Text Scope
             * @default full_text
             */
            text_scope: string;
        };
        /** QueryInfo */
        QueryInfo: {
            /** Interpreted Query */
            interpreted_query: string;
            /** Intent */
            intent: string;
            /**
             * Lang
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
            /**
             * Query Lang
             * @default en
             * @enum {string}
             */
            query_lang: "en" | "hi" | "kn";
            /** Resolved Scope */
            resolved_scope: components["schemas"]["ScopeItemOut"][];
            /** Scope Source */
            scope_source: string;
            /** Rewritten */
            rewritten: boolean;
            /** Notes */
            notes: string[];
        };
        /** ReferenceOut */
        ReferenceOut: {
            /** Number */
            number: string;
            /** Slug */
            slug: string | null;
            /** Title */
            title: string | null;
            /** Clause Number */
            clause_number: string | null;
        };
        /** RelatedOut */
        RelatedOut: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
            /** Similarity */
            similarity: number;
        };
        /** RequirementOut */
        RequirementOut: {
            /** Id */
            id: number;
            /** Clause Number */
            clause_number: string;
            /** Clause Heading */
            clause_heading: string;
            /** Clause Kind */
            clause_kind: string;
            /**
             * Modality
             * @enum {string}
             */
            modality: "shall" | "shall_not" | "should" | "should_not" | "may" | "must";
            /** Text */
            text: string;
            /** Page */
            page: number;
            /** Topic */
            topic: string;
        };
        /** RequirementsOut */
        RequirementsOut: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /** Synthetic */
            synthetic: boolean;
            /** Items */
            items: components["schemas"]["RequirementOut"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** STTOut */
        STTOut: {
            /** Text */
            text: string;
            /** No Speech */
            no_speech: boolean;
            /** Language */
            language: string | null;
            /** Requested Language */
            requested_language: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Ms */
            ms: number;
        };
        /** ScopeItemOut */
        ScopeItemOut: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
        };
        /** Scores */
        Scores: {
            /** Lexical Rank */
            lexical_rank: number | null;
            /** Vector */
            vector: number | null;
            /** Fused */
            fused: number | null;
            /** Rerank */
            rerank: number | null;
            /** Boosts */
            boosts: {
                [key: string]: number;
            };
        };
        /** SearchFilters */
        SearchFilters: {
            /** Kinds */
            kinds?: ("standard" | "guidance" | "order" | "catalogue")[];
            /** Slugs */
            slugs?: string[];
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
            filters?: components["schemas"]["SearchFilters"] | null;
            context?: components["schemas"]["AskContext"] | null;
        };
        /** SearchResponse */
        SearchResponse: {
            query: components["schemas"]["QueryInfo"];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Standards */
            standards: components["schemas"]["StandardRef"][];
            /** Timings */
            timings: {
                [key: string]: number;
            };
            /** Total Candidates */
            total_candidates: number;
        };
        /** StandardDetail */
        StandardDetail: {
            summary: components["schemas"]["StandardSummary"];
            /** Revision Label */
            revision_label: string | null;
            /** Status Verified On */
            status_verified_on: string | null;
            /** Committee */
            committee: string | null;
            /** Ics */
            ics: string | null;
            /** Industries */
            industries: string[];
            /** Products */
            products: string[];
            provenance: components["schemas"]["Provenance"];
            compulsory: components["schemas"]["CompulsoryEvidence"];
            /** Scope Text */
            scope_text: string | null;
            /** Scope Clause */
            scope_clause: string | null;
            /** Clauses */
            clauses: components["schemas"]["ClauseNode"][];
            /** Amendments */
            amendments: components["schemas"]["AmendmentOut"][];
            /** References */
            references: components["schemas"]["ReferenceOut"][];
            /** Referenced By */
            referenced_by: components["schemas"]["ReferenceOut"][];
            /** Related */
            related: components["schemas"]["RelatedOut"][];
            /** Terms */
            terms: {
                [key: string]: string | number;
            }[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Product Mentions */
            product_mentions: {
                [key: string]: string | null;
            }[];
        };
        /** StandardListOut */
        StandardListOut: {
            /** Items */
            items: components["schemas"]["StandardSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Facets */
            facets: {
                [key: string]: components["schemas"]["CategoryCount"][];
            };
        };
        /** StandardRef */
        StandardRef: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
            /** Why */
            why: string | null;
            /** Citations */
            citations: string[];
            /**
             * Compulsory
             * @default unknown
             */
            compulsory: string;
            /** Compulsory Source */
            compulsory_source: string | null;
            /**
             * Catalogue Only
             * @default false
             */
            catalogue_only: boolean;
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Via
             * @default full_text
             */
            via: string;
            /** Matched Row */
            matched_row: string | null;
        };
        /** StandardSummary */
        StandardSummary: {
            /** Slug */
            slug: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Category */
            category: string | null;
            /** Status */
            status: string;
            /** Compulsory */
            compulsory: string;
            /** Catalogue Only */
            catalogue_only: boolean;
            /** Synthetic */
            synthetic: boolean;
            /** Needs Review */
            needs_review: boolean;
            /** Tier */
            tier: string;
            /**
             * Text Scope
             * @default full_text
             */
            text_scope: string;
            /** Source Type */
            source_type: string | null;
            /**
             * Clause Count
             * @default 0
             */
            clause_count: number;
            /**
             * Requirement Count
             * @default 0
             */
            requirement_count: number;
        };
        /** SuggestItem */
        SuggestItem: {
            /** Slug */
            slug: string;
            /** Number */
            number: string | null;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "standard" | "guidance" | "order" | "catalogue";
        };
        /** SummaryOut */
        SummaryOut: {
            /** Slug */
            slug: string;
            answer: components["schemas"]["Answer"];
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** TTSRequest */
        TTSRequest: {
            /** Text */
            text: string;
            /**
             * Lang
             * @default en
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
        };
        /** Timings */
        Timings: {
            /** Stages */
            stages: {
                [key: string]: number;
            };
            /** Total Ms */
            total_ms: number;
        };
        /** TranslateOut */
        TranslateOut: {
            /** Available */
            available: boolean;
            /** Translations */
            translations: string[];
        };
        /**
         * TranslateRequest
         * @description Machine translation of quoted source passages for display under the original (never replacing it).
         */
        TranslateRequest: {
            /** Texts */
            texts: string[];
            /**
             * Lang
             * @enum {string}
             */
            lang: "en" | "hi" | "kn";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceStatus */
        VoiceStatus: {
            /** Stt Available */
            stt_available: boolean;
            /** Stt Provider */
            stt_provider: string | null;
            /** Stt Model */
            stt_model: string | null;
            /** Stt Languages */
            stt_languages: string[];
            /** Tts Available */
            tts_available: boolean;
            /** Tts Provider */
            tts_provider: string | null;
            /** Tts Languages */
            tts_languages: string[];
            /** Tts Problem */
            tts_problem: string | null;
            /** Max Seconds */
            max_seconds: number;
            /** Max Bytes */
            max_bytes: number;
        };
        /** StageEvent */
        StageEvent: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "understanding" | "searching" | "drafting" | "verifying" | "translating";
            /** Detail */
            detail: {
                [key: string]: number | string;
            };
        };
        /** EvidenceEvent */
        EvidenceEvent: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Standards */
            standards: components["schemas"]["StandardRef"][];
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Code */
            code: string;
            /** Message Key */
            message_key: string;
        };
        /** DoneEvent */
        DoneEvent: {
            /** Request Id */
            request_id: string;
            timings: components["schemas"]["Timings"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    compare_api_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translate_api_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_status_endpoint_api_voice_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceStatus"];
                };
            };
        };
    };
    voice_stt_api_voice_stt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_voice_stt_api_voice_stt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["STTOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_tts_api_voice_tts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TTSRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_summary_api_eval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debug_trace_api_debug_trace__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_endpoint_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_endpoint_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryOut"];
                };
            };
        };
    };
    list_standards_api_standards_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: string | null;
                category?: string | null;
                compulsory?: string | null;
                tier?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                sort?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_standards_suggest_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    standard_detail_api_standards__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_clauses_api_standards__slug__clauses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClauseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clause_api_standards__slug__clauses__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClauseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requirements_api_standards__slug__requirements_get: {
        parameters: {
            query?: {
                modality?: string | null;
                kind?: string | null;
                q?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requirements_plain_api_standards__slug__requirements_plain_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requirements_csv_api_standards__slug__requirements_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_standards__slug__summary_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_api_standards__slug__pages__n__png_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path: {
                slug: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
