"""Provenance manifest (data/sources.yaml) and dataset discovery.

Every indexed file has one manifest entry recording where it came from (tier, URL, retrieval date,
status, category, compulsory-certification evidence ...). The manifest always wins over values
guessed from the document text.

Tiers (see docs/DATA.md):
  A  real Indian Standards placed by the team in data/raw/ (obtained through official BIS channels)
  B  official public BIS pages / orders fetched by `bisense fetch-public` into data/public/
  C  synthetic demo pack rendered from data/demo/*.md (clearly labelled, never presented as real)

Dataset modes (DATASET env var):
  auto  A + B when Tier A has documents, otherwise B + C
  real  A + B
  demo  B + C
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import yaml

from bisense.ingest.demo_pack import read_demo_source
from bisense.ingest.fetch_public import load_fetch_log, load_public_sources

MANIFEST_FIELDS = [
    "file", "tier", "standard_number", "title", "doc_type", "source_url", "obtained_on", "status",
    "status_verified_on", "category", "industries", "products", "compulsory_certification",
    "compulsory_source", "language", "synthetic", "needs_review",
]


@dataclass
class SourceFile:
    path: Path
    tier: str
    entry: dict
    drafted: bool = False


@dataclass
class Discovery:
    files: list[SourceFile]
    dataset_mode: str  # "real" | "demo" (what is actually loaded)
    tiers: list[str]
    drafted: list[str] = field(default_factory=list)


def manifest_path(data_dir: Path) -> Path:
    return data_dir / "sources.yaml"


def load_manifest(data_dir: Path) -> dict[str, dict]:
    path = manifest_path(data_dir)
    if not path.exists():
        return {}
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {e["file"]: e for e in raw.get("documents", []) if isinstance(e, dict) and e.get("file")}


def save_manifest(data_dir: Path, entries: dict[str, dict]) -> None:
    ordered = sorted(entries.values(), key=lambda e: (e.get("tier", "Z"), e["file"]))
    header = (
        "# BISense provenance manifest: one entry per indexed file.\n"
        "# Tier A entries are written by the team (see docs/DATA.md). Tier B and C entries are\n"
        "# regenerated by `bisense ingest` from data/public_sources.yaml + data/public/fetch_log.yaml\n"
        "# and from the front matter of data/demo/*.md. Edit Tier A entries by hand; set\n"
        "# needs_review: false once a person has verified number, title and status on the BIS website.\n"
    )
    body = yaml.safe_dump({"documents": ordered}, sort_keys=False, allow_unicode=True, width=110)
    tmp = manifest_path(data_dir).with_suffix(".yaml.tmp")
    tmp.write_text(header + body, encoding="utf-8")
    tmp.replace(manifest_path(data_dir))


def _tier_c_entries(data_dir: Path) -> dict[str, dict]:
    out = {}
    for src in sorted((data_dir / "demo").glob("*.md")):
        meta, _ = read_demo_source(src)
        name = src.stem + ".pdf"
        out[name] = {
            "file": name,
            "tier": "C",
            "standard_number": meta["number"],
            "title": meta["title"],
            "doc_type": "synthetic_demo",
            "source_url": None,
            "obtained_on": None,
            "status": "unknown",
            "status_verified_on": None,
            "category": meta.get("category"),
            "industries": meta.get("industries", []),
            "products": meta.get("products", []),
            "compulsory_certification": "unknown",
            "compulsory_source": None,
            "language": "en",
            "synthetic": True,
            "needs_review": False,
            "revision": meta.get("revision"),
            "committee": meta.get("committee"),
            "ics": meta.get("ics"),
        }
    return out


def _tier_b_entries(data_dir: Path) -> dict[str, dict]:
    log = load_fetch_log(data_dir)
    out = {}
    for page in load_public_sources(data_dir):
        name = page["file"]
        if name not in log or not (data_dir / "public" / name).exists():
            continue
        out[name] = {
            "file": name,
            "tier": "B",
            "standard_number": None,
            "title": page["title"],
            "doc_type": page.get("doc_type", "guidance_page"),
            "source_url": page["url"],
            "obtained_on": log[name]["obtained_on"],
            "status": "current",
            "status_verified_on": log[name]["obtained_on"],
            "category": page.get("category"),
            "industries": [],
            "products": [],
            "compulsory_certification": "unknown",
            "compulsory_source": None,
            "language": page.get("language", "en"),
            "synthetic": False,
            "needs_review": False,
        }
    return out


def draft_entry(path: Path, detected_number: str | None, detected_title: str | None) -> dict:
    """Manifest entry for a Tier A file nobody has described yet (flagged for review)."""
    return {
        "file": path.name,
        "tier": "A",
        "standard_number": detected_number,
        "title": detected_title or path.stem,
        "doc_type": "standard",
        "source_url": None,
        "obtained_on": date.fromtimestamp(path.stat().st_mtime).isoformat(),
        "status": "unknown",
        "status_verified_on": None,
        "category": None,
        "industries": [],
        "products": [],
        "compulsory_certification": "unknown",
        "compulsory_source": None,
        "language": "en",
        "synthetic": False,
        "needs_review": True,
    }


def discover(data_dir: Path, dataset: str = "auto") -> tuple[Discovery, dict[str, dict]]:
    """Find the files to index for the requested dataset mode and merge the manifest."""
    manifest = load_manifest(data_dir)
    raw_dir = data_dir / "raw"
    tier_a = sorted(p for p in raw_dir.glob("*.pdf")) if raw_dir.exists() else []

    if dataset == "real":
        tiers = ["A", "B"]
    elif dataset == "demo":
        tiers = ["B", "C"]
    else:
        tiers = ["A", "B"] if tier_a else ["B", "C"]

    # Regenerate B and C entries; keep A entries (hand-written) as they are.
    entries = {k: v for k, v in manifest.items() if v.get("tier") == "A"}
    entries.update(_tier_b_entries(data_dir))
    entries.update(_tier_c_entries(data_dir))

    files: list[SourceFile] = []
    if "A" in tiers:
        for p in tier_a:
            e = entries.get(p.name)
            files.append(SourceFile(p, "A", e or {}, drafted=e is None))
    if "B" in tiers:
        for name, e in entries.items():
            if e.get("tier") == "B":
                files.append(SourceFile(data_dir / "public" / name, "B", e))
    if "C" in tiers:
        for name, e in entries.items():
            if e.get("tier") == "C":
                files.append(SourceFile(data_dir / "demo" / "pdf" / name, "C", e))

    mode = "demo" if "C" in tiers else "real"
    return Discovery(files=files, dataset_mode=mode, tiers=tiers), entries
