"""Provenance manifest (data/sources.yaml) and dataset discovery.

Every indexed file has one manifest entry recording where it came from. The manifest always wins over
values guessed from the document text.

Tiers (see docs/DATA.md):
  A  Official BIS documents: standards the team downloads with its own legitimate BIS account
     (data/raw/), and official BIS PDFs such as product manuals and guidelines (data/public/).
  B  Official BIS website: public pages and listings (certification schemes, FAQs, lists of products
     under compulsory certification) fetched by `bisense fetch-public` (data/public/).
  C  Government notifications: Quality Control Orders / Gazette notifications (data/public/).
  D  Sample data written for this project (data/demo/). NOT official. Excluded unless DATASET=sample.

Dataset modes (DATASET env var):
  official (default)  Tiers A + B + C only.
  sample              A + B + C + the Tier D sample pack, labelled "Sample data, not official" everywhere.
  (Older values: auto/real -> official, demo -> sample.)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import yaml

from bisense.ingest.demo_pack import read_demo_source
from bisense.ingest.fetch_public import load_fetch_log, load_public_sources

MANIFEST_FIELDS = [
    "file",
    "tier",
    "location",
    "standard_number",
    "title",
    "doc_type",
    "source_type",
    "source_org",
    "source_url",
    "obtained_on",
    "status",
    "status_verified_on",
    "verification_status",
    "access_note",
    "category",
    "industries",
    "products",
    "compulsory_certification",
    "compulsory_source",
    "language",
    "synthetic",
    "needs_review",
]

BIS = "Bureau of Indian Standards"

# doc_type -> (tier, source_type)
DOC_TYPES: dict[str, tuple[str, str]] = {
    "standard": ("A", "official_document"),
    "product_manual": ("A", "official_document"),
    "guidance_pdf": ("A", "official_document"),
    "guidance_page": ("B", "official_website"),
    "catalogue_page": ("B", "official_website"),
    "government_order": ("C", "government_notification"),
    "synthetic_demo": ("D", "sample"),
}


@dataclass
class SourceFile:
    path: Path
    tier: str
    entry: dict
    drafted: bool = False


@dataclass
class Discovery:
    files: list[SourceFile]
    dataset_mode: str  # "official" | "sample"
    tiers: list[str]
    drafted: list[str] = field(default_factory=list)


def normalize_mode(dataset: str) -> str:
    return "sample" if dataset in ("sample", "demo") else "official"


def manifest_path(data_dir: Path) -> Path:
    return data_dir / "sources.yaml"


def load_manifest(data_dir: Path) -> dict[str, dict]:
    path = manifest_path(data_dir)
    if not path.exists():
        return {}
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {e["file"]: e for e in raw.get("documents", []) if isinstance(e, dict) and e.get("file")}


def save_manifest(data_dir: Path, entries: dict[str, dict]) -> None:
    ordered = sorted(entries.values(), key=lambda e: (e.get("tier", "Z"), e["file"]))
    header = (
        "# BISense provenance manifest: one entry per indexed file.\n"
        "# Entries with location: raw are written by the team (standards downloaded with your own BIS account;\n"
        "# see docs/DATA.md). Entries for data/public and data/demo are regenerated by `bisense ingest`\n"
        "# from data/public_sources.yaml + data/public/fetch_log.yaml and data/demo/*.md.\n"
        "# Set verification_status: verified (and needs_review: false) only after checking the number, title and\n"
        "# status on the official BIS website.\n"
    )
    body = yaml.safe_dump({"documents": ordered}, sort_keys=False, allow_unicode=True, width=110)
    tmp = manifest_path(data_dir).with_suffix(".yaml.tmp")
    tmp.write_text(header + body, encoding="utf-8")
    tmp.replace(manifest_path(data_dir))


def _sample_entries(data_dir: Path) -> dict[str, dict]:
    out = {}
    for src in sorted((data_dir / "demo").glob("*.md")):
        meta, _ = read_demo_source(src)
        name = src.stem + ".pdf"
        out[name] = {
            "file": name,
            "tier": "D",
            "location": "demo",
            "standard_number": meta["number"],
            "title": meta["title"],
            "doc_type": "synthetic_demo",
            "source_type": "sample",
            "source_org": "BISense sample data (not official)",
            "source_url": None,
            "obtained_on": None,
            "status": "unknown",
            "status_verified_on": None,
            "verification_status": "sample",
            "access_note": "Written for this project to demonstrate features. Not an Indian Standard.",
            "category": meta.get("category"),
            "industries": meta.get("industries", []),
            "products": meta.get("products", []),
            "compulsory_certification": "unknown",
            "compulsory_source": None,
            "language": "en",
            "synthetic": True,
            "needs_review": False,
            "revision": meta.get("revision"),
            "committee": meta.get("committee"),
            "ics": meta.get("ics"),
        }
    return out


def _public_entries(data_dir: Path) -> dict[str, dict]:
    log = load_fetch_log(data_dir)
    out = {}
    for page in load_public_sources(data_dir):
        name = page["file"]
        if name not in log or not (data_dir / "public" / name).exists():
            continue
        doc_type = page.get("doc_type", "guidance_page")
        if doc_type == "guidance_page" and name.lower().endswith(".pdf"):
            doc_type = "guidance_pdf"
        tier, source_type = DOC_TYPES.get(doc_type, ("B", "official_website"))
        is_order = doc_type == "government_order"
        out[name] = {
            "file": name,
            "tier": tier,
            "location": "public",
            "standard_number": page.get("standard_number"),
            "title": page["title"],
            "standard_title": page.get("standard_title"),
            "doc_type": doc_type,
            "source_type": source_type,
            "source_org": "Government of India (Gazette notification, published on bis.gov.in)" if is_order else BIS,
            "source_url": page["url"],
            "obtained_on": log[name]["obtained_on"],
            "status": "current",
            "status_verified_on": log[name]["obtained_on"],
            # Content was downloaded directly from the official domain on obtained_on.
            "verification_status": "verified",
            "access_note": "Public page/document on www.bis.gov.in; indexed locally with its URL and retrieval date.",
            "category": page.get("category"),
            "industries": [],
            "products": [],
            "compulsory_certification": "unknown",
            "compulsory_source": None,
            "language": page.get("language", "en"),
            "synthetic": False,
            "needs_review": False,
        }
    return out


def draft_entry(path: Path, detected_number: str | None, detected_title: str | None) -> dict:
    """Manifest entry for a team-supplied file nobody has described yet (flagged for review)."""
    return {
        "file": path.name,
        "tier": "A",
        "location": "raw",
        "standard_number": detected_number,
        "title": detected_title or path.stem,
        "doc_type": "standard",
        "source_type": "official_document",
        "source_org": BIS,
        "source_url": None,
        "obtained_on": date.fromtimestamp(path.stat().st_mtime).isoformat(),
        "status": "unknown",
        "status_verified_on": None,
        "verification_status": "unverified",
        "access_note": "Downloaded by the team through an official BIS channel; not redistributed.",
        "category": None,
        "industries": [],
        "products": [],
        "compulsory_certification": "unknown",
        "compulsory_source": None,
        "language": "en",
        "synthetic": False,
        "needs_review": True,
    }


def _complete_raw_entry(e: dict) -> dict:
    """Fill provenance defaults for hand-written entries of team-supplied standards."""
    e = dict(e)
    e.setdefault("tier", "A")
    e["location"] = "raw"
    e.setdefault("doc_type", "standard")
    e.setdefault("source_type", "official_document")
    e.setdefault("source_org", BIS)
    e.setdefault("verification_status", "unverified" if e.get("needs_review", True) else "verified")
    e.setdefault("access_note", "Downloaded by the team through an official BIS channel; not redistributed.")
    return e


def discover(data_dir: Path, dataset: str = "official") -> tuple[Discovery, dict[str, dict]]:
    """Find the files to index for the requested dataset mode and merge the manifest."""
    mode = normalize_mode(dataset)
    manifest = load_manifest(data_dir)
    raw_dir = data_dir / "raw"
    raw_files = sorted(p for p in raw_dir.glob("*.pdf")) if raw_dir.exists() else []

    # Team-written entries for data/raw are kept; public and sample entries are regenerated.
    entries = {k: _complete_raw_entry(v) for k, v in manifest.items() if v.get("location", "raw" if v.get("tier") == "A" else "") == "raw"}
    entries.update(_public_entries(data_dir))
    if mode == "sample":
        entries.update(_sample_entries(data_dir))

    files: list[SourceFile] = []
    for p in raw_files:
        e = entries.get(p.name)
        files.append(SourceFile(p, "A", e or {}, drafted=e is None))
    for name, e in entries.items():
        if e.get("location") == "public":
            files.append(SourceFile(data_dir / "public" / name, e["tier"], e))
        elif e.get("location") == "demo":
            files.append(SourceFile(data_dir / "demo" / "pdf" / name, "D", e))

    tiers = sorted({f.tier for f in files})
    return Discovery(files=files, dataset_mode=mode, tiers=tiers), entries
